apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: basket-react-component-components
  namespace: experiments
  description: React component library for the basket system
spec:
  targets:
    - ./components/*.yaml